development:
  #url: http://128321-9-0-052da3.runbot9.odoo.com         #the OpenERP XML/RPC server
  #database: 128321-9-0-052da3-all               #the OpenERP database you want to connect to
  #  url: http://151512-9-0-f558c0.runbot.odoo.com
  #  database: 151512-9-0-f558c0-all
  url: http://voodooakreshop2_odoo_run_1:8069
  database: db
  username: admin
  password: admin
  authenticate_ooorest: true
  bootstrap: true
  global_context:
    'lang': en_US
  aliases:
    en_US:
      products: product.template
  param_keys:
    product.template: name
  proxies:
    "/web/image": http://voodooakreshop2_odoo_run_1:8069/web/image
    "/web/content": http://voodooakreshop2_odoo_run_1:8069/web/content
    "/shop/cart": http://voodooakreshop2_odoo_run_1:8069/shop/cart
    "/shop/checkout": http://voodooakreshop2_odoo_run_1:8069/shop/checkout
    "/shop/confirm_order": http://voodooakreshop2_odoo_run_1:8069/shop/confirm_order
    "/shop/payment": http://voodooakreshop2_odoo_run_1:8069/shop/payment
    "/shop/confirmation": http://voodooakreshop2_odoo_run_1:8069/shop/confirmation

