development:
  #url: http://128321-9-0-052da3.runbot9.odoo.com         #the OpenERP XML/RPC server
  #database: 128321-9-0-052da3-all               #the OpenERP database you want to connect to
  url: http://odoo:8069
  database: db
  username: admin
  password: admin
  authenticate_ooorest: true
  bootstrap: true
  global_context:
    'lang': en_US
  aliases:
    en_US:
      products: product.template
  param_keys:
    product.template: name
  proxies:
    "/web/image": http://odoo:8069/web/image
    "/web/content": http://odoo:8069/web/content
    "/shop/cart": http://odoo:8069/shop/cart

